<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Jp" failures="2" tests="4" name="Test" time="1.065" errors="0" timestamp="2022-03-28T22:28:37 PDT">
  <testcase classname="listeners.TestClass1" name="testMethod3" time="1.016">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method listeners.TestClass1.testMethod3() didn&amp;apos;t finish within the time-out 1000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method listeners.TestClass1.testMethod3() didn't finish within the time-out 1000
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- testMethod3 -->
  <testcase classname="listeners.TestClass1" name="testMethod1" time="0.001"/>
  <testcase classname="listeners.TestClass1" name="testMethod2" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at listeners.TestClass1.testMethod2(TestClass1.java:22)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testMethod2 -->
  <testcase classname="listeners.TestClass1" name="testMethod4" time="0.0">
    <skipped/>
  </testcase> <!-- testMethod4 -->
</testsuite> <!-- Test -->
